package com.kyphipraniti.fitnesstasks.model;

import java.util.ArrayList;
import java.util.Arrays;

public class ListOfExercises {

    public static ArrayList<String> aListExercise = new ArrayList<>(Arrays.asList("Weighted Crunch",
        "Weighted Leg Raise",
        "Dumbbell Side Bend",
        "Bench Press",
        "Bench Press (Neutral Grip)",
        "Incline Bench Press",
        "Incline Bench Press (Neutral Grip)",
        "Decline Bench Press",
        "Lying Fly",
        "Incline Fly",
        "Straight-Arm Pullover",
        "Bent-Arm Pullover",
        "Palms-In Shoulder Press",
        "Back Supported Palms-In Shoulder Press",
        "Palms-In Alternated Shoulder Press",
        "Seated Palms-In Alternated Shoulder Press",
        "Shoulder Press",
        "Seated Shoulder Press",
        "Back Supported Shoulder Press",
        "Lateral Raise",
        "Bent-Over One-Arm Deltoid Raise",
        "Seated Side Lateral Raise",
        "Bent-Over Rear Deltoid Raise",
        "Rear Deltoid Raise",
        "Rear Deltoid Circle",
        "Straight-Arm Front Deltoid Raise",
        "Upright Row",
        "Front Raise",
        "Shoulder Shrug",
        "Push Press",
        "Crouched Rear Deltoid Row",
        "One-at-a-Time Biceps Curl",
        "Alternated Biceps Curl",
        "Inner-Biceps Curl",
        "Biceps Curl",
        "Hammer Curl",
        "Seated Alternated Biceps Curl",
        "Seated Biceps Curl",
        "Incline Alternated Biceps Curl",
        "Incline Biceps Curl",
        "Incline Biceps Bench Curl",
        "Concentration Biceps Curl",
        "Seated Inner-Biceps Curl",
        "Seated Concentration Curl",
        "Seated Isolated Dumbbell Curl",
        "Preacher Biceps Curl (Supination Grip)",
        "Preacher Biceps Curl (Neutral Grip)",
        "Bench Alternated Biceps Curl",
        "Supine Biceps Curl",
        "Two-Arms Triceps Extension",
        "One-Arm Triceps Extension",
        "Seated Triceps Extension",
        "Triceps Kickback",
        "Bent-Over One-Arm Triceps Extension",
        "Lying Triceps Extension",
        "Triceps Bench Press",
        "Wide Row",
        "Bent Over Row",
        "Kneeling One Arm Row",
        "One Arm Row",
        "Dead Lift",
        "Stiff Legged Dead Lift",
        "Bend to Opposite Foot",
        "Twisting Bend to Opposite Foot",
        "Back Fly",
        "Squat",
        "Reverse Lunge",
        "Stationary Lunge",
        "Side Lunge",
        "Dumbbell Swing Through",
        "Stiff Legged Dead Lift",
        "Toe Raise",
        "One Legged Toe Raise",
        "Seated One Legged Toe Raise",
        "Palms-Up Wrist Curl",
        "One-Arm Palm-Up Wrist Curlv",
        "Palms-Down Wrist Curl",
        "One-Arm Palm-Down Wrist Curl"));

}
